document.getElementById('header-container').style.background = '#00b069';
document.getElementById('container').style.background = '#f3f3f3';
document.getElementById('footer-container').style.background = '#003533';
document.getElementsByTagName('div')[0].style.background = '#FF9F84';
document.getElementsByTagName('div')[1].style.background = '#FF9F84';
document.getElementsByTagName('div')[2].style.background = '#f9db5e';
document.getElementsByTagName('div')[3].style.background = '#f9db5e';
document.getElementsByTagName('h3')[0].style.background = '#a500f3';
document.getElementsByTagName('h3')[1].style.background = '#a500f3';
document.getElementsByTagName('h3')[2].style.background = '#232525';
document.getElementsByTagName('h3')[3].style.background = '#232525';
document.querySelector('.no-emergency-tasks').style.background = '#f9db5e'
// document.getElementsByClassName('no-emergency-tasks').style.background = '#f9db5e'
document.querySelector('.emergency-tasks').style.background = '#FF9F84'
// document.querySelector('emergency-tasks').style.background = '#f9db5e'
